# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0fc5b6355a71fe67a5dcd74b7387726f1718dc5e0ae73ff8e4c166318048e7cd7635b9b65ee8164240b2d1d75cab709798a05430861c86707deb6b4ce270801

test:
  secret_key_base: 94239b2c0813af5462cf0714e083d390e8d67136f508ac318d20be561941adcca7403281791ec057af64dba47f0b98cfc6fcdba10f0c4ee9fb3276ac979afc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
